name: Main Action

on:
  push:
    workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup Node.js environment
      - uses: actions/setup-node@v2
        with:
          node-version: "16" # Specify the Node.js version you want to use

      - run: npm ci

      # ESLint
      - name: Install ESLint
        run: npm run lint
