name: Main Action

on:
  push:
    workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 8.0.0
      - run: pnpm i --frozen-lockfile

      # ESLint
      - name: Install ESLint
        run: pnpm lint
