name: type-check

on:
  push:

jobs:
  call-workflow:
    uses: .github/workflows/main.yaml

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Typecheck
        uses: andoshin11/typescript-error-reporter-action@v1.0.2
