name: type-check

on:
  push:
    branches-ignore:
      - "deployment/**"

jobs:
  call-workflow:
    uses: code-yy/yutodev/.github/workflows/main.yaml@v1

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Typecheck
        uses: andoshin11/typescript-error-reporter-action@v1.0.2
